name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: build
        run: npm run build
