name: Build and deploy
on:
  push:
    branches: [master]

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Use npm
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: npm install
      - name: build
        run: CI=false npm run build
