name: Build and deploy

on:

  push:

    branches: [master]

jobs:

  build:

    name: Building

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo

        uses: actions/checkout@master

      - name: Use npm

        uses: actions/setup-node@v1

        with:

          node-version: 12.x

      - name: install

        run: npm install

      - name: build

        run: CI=false npm run build

        

  commit:

     name: Committing

     needs: build

     runs-on: ubuntu-latest

     steps:

       

       - name: Config username

         run: git config --global user.name 'BalazsGyulai'

       - name: Config email

         run: git config --global user.email 'trombita0531@gmail.com'

       - name: Add

         run: git add .

       - name: Commit

         run: git commit -m "Automated commit"

       - name: Push

         run: git push
