name: Push commit

on: push

jobs:

  report:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: Create report file

        run: date +%s > report.txt

      - name: Commit report

        run: |

          git config --global user.name 'BalazsGyulai'

          git config --global user.email 'trombita0531@gmail.com'
          
          git add .

          git commit -m "Automated report"

          git push origin build
